// Generated by gencpp from file ur_modern_driver/RG2_Grip.msg
// DO NOT EDIT!


#ifndef UR_MODERN_DRIVER_MESSAGE_RG2_GRIP_H
#define UR_MODERN_DRIVER_MESSAGE_RG2_GRIP_H

#include <ros/service_traits.h>


#include <ur_modern_driver/RG2_GripRequest.h>
#include <ur_modern_driver/RG2_GripResponse.h>


namespace ur_modern_driver
{

struct RG2_Grip
{

typedef RG2_GripRequest Request;
typedef RG2_GripResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RG2_Grip
} // namespace ur_modern_driver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ur_modern_driver::RG2_Grip > {
  static const char* value()
  {
    return "e59cc69aa535dfedb8f29528fe2a1de3";
  }

  static const char* value(const ::ur_modern_driver::RG2_Grip&) { return value(); }
};

template<>
struct DataType< ::ur_modern_driver::RG2_Grip > {
  static const char* value()
  {
    return "ur_modern_driver/RG2_Grip";
  }

  static const char* value(const ::ur_modern_driver::RG2_Grip&) { return value(); }
};


// service_traits::MD5Sum< ::ur_modern_driver::RG2_GripRequest> should match 
// service_traits::MD5Sum< ::ur_modern_driver::RG2_Grip > 
template<>
struct MD5Sum< ::ur_modern_driver::RG2_GripRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ur_modern_driver::RG2_Grip >::value();
  }
  static const char* value(const ::ur_modern_driver::RG2_GripRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ur_modern_driver::RG2_GripRequest> should match 
// service_traits::DataType< ::ur_modern_driver::RG2_Grip > 
template<>
struct DataType< ::ur_modern_driver::RG2_GripRequest>
{
  static const char* value()
  {
    return DataType< ::ur_modern_driver::RG2_Grip >::value();
  }
  static const char* value(const ::ur_modern_driver::RG2_GripRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ur_modern_driver::RG2_GripResponse> should match 
// service_traits::MD5Sum< ::ur_modern_driver::RG2_Grip > 
template<>
struct MD5Sum< ::ur_modern_driver::RG2_GripResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ur_modern_driver::RG2_Grip >::value();
  }
  static const char* value(const ::ur_modern_driver::RG2_GripResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ur_modern_driver::RG2_GripResponse> should match 
// service_traits::DataType< ::ur_modern_driver::RG2_Grip > 
template<>
struct DataType< ::ur_modern_driver::RG2_GripResponse>
{
  static const char* value()
  {
    return DataType< ::ur_modern_driver::RG2_Grip >::value();
  }
  static const char* value(const ::ur_modern_driver::RG2_GripResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UR_MODERN_DRIVER_MESSAGE_RG2_GRIP_H
